server.port=8080
spring.application.name=inventory-system

spring.datasource.url=jdbc:mysql://localhost:3306/mile_3

spring.datasource.username=inventory_user
spring.datasource.password=Ruchi524#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sainiruchi2471@gmail.com
spring.mail.password=rvmjtfxauvupfxiv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App
app.jwt.secret=InventorySystemSecretKeyForJWTSigningAndValidation2024
app.jwt.expiration=86400000

# Logging
logging.level.com.inventory=DEBUG
logging.level.org.springframework.security=DEBUG